### ISSUE TITLE
v8 vs nas

### ISSUE THREAD

**Issue by srubenacker** [Hyuto/yolo-nas-onnx#2]
When performing inference on the web using onnx runtime, do you recommend yolov8 or yolo nas?  In your experience, which is faster?  Which is more accurate?  Also, are you using int8 quantization for yolo nas?

**Comment by Hyuto** [comment]
Hello, from my perspective I think the best model to deploy right at the edge on the web is the smaller one. Because you don't want the user get bored watching the loading screen to wait the model is loaded. YOLOv8 give a smaller model which is `yolov8n` the smallest model which is around 13 MB if you compare it with the smallest YOLO-NAS model which is `yolo_nas_s` have the size around 48 MB. The smallest YOLO-NAS model is in par with `yolov8s` with 43 MB size. 

For inferencing I haven't do benchmark yet since benchmarking model in the web is a pain 😀 .

But if you take a look of the performance YOLO-NAS claimed they have better MAP than YOLOv8 shown in the image bellow,

![YOLO-NAS](https://raw.githubusercontent.com/Deci-AI/super-gradients/master/documentation/source/images/yolo_nas_frontier.png)

And the official YOLOv8 repo hasn't update the model yet so I expect YOLO-NAS have a better detection.

I haven't tried quantization on YOLO-NAS model  but I expect the size doesn't drop to the level of `yolov8n` model.

**Comment by srubenacker** [comment]
Thanks!  I appreciate your thorough response.
