### ISSUE TITLE
Batch mode

### ISSUE THREAD

**Issue by olivierbeauve** [Hyuto/yolo-nas-onnx#3]
Hello!

Is it possible to easily adapt the code to work in batch mode (one input with multiple images)? Perhaps we also need to modify the process of generating the ONNX model?

Thank you!

**Comment by Hyuto** [comment]
Hello, I don't think to implement batch mode on this project since the code base will be more complex and need bunch of stuff to add. My goal for this project is to keep the code simple for readable purpose, and implementing batch mode will get the code more complex especially on the postprocess because OpenCV doesn't come with batched NMS like Pytorch.
