### ISSUE TITLE
C++ Version crash

### ISSUE THREAD

**Issue by xellDart** [Hyuto/yolo-nas-onnx#5]
Hi!, Thanks for your help, I have a problem using custom model, on python version all works, but on c++ version i get

handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Squeeze]:(/model/heads/Squeeze_output_0)

I already get metadata, but i cant fix this

**Comment by Hyuto** [comment]
Hello, Thanks for the feedback.

I think the `opset_version` is the main problem here. If you use older OpenCV version than `4.7.0` it may be break, because the older version doesn't support many ONNX operators. By default YOLO-NAS onnx exported model is set to `opset_version=14`. 

You can solve this issue by either update your OpenCV version to the latest (it works well on v4.7.0) or Set the opset version of YOLO-NAS onnx model to lower version. You can set the opeset version on the exporting script

```python
from super_gradients.training import models

net = models.get("yolo_nas_s", pretrained_weights="coco")
models.convert_to_onnx(model=net, input_shape=(3, 640, 640), out_path='yolo_nas_s.onnx', 
                       torch_onnx_export_kwargs={"opset_version": <OPSET_VERSION>})
```

I've tested `opset_version=12` work well on OpenCV v4.5.5

**Comment by xellDart** [comment]
Thanks!! Im update my opencv, now is working
